adactive_sas_saml2_bridge:
    hosted:
        metadata_route: sonata_login
        identity_provider:
            enabled: true
            service_provider_repository: app.saml.service_provider_repository
            sso_route: sonata_login
            sls_route: sonata_logout
            login_route: sonata_login
            logout_route: sonata_logout
            public_key: '%idp_public_key_file_path%'
            private_key: '%idp_private_key_file_path%'
#            logout:
#                handlers: [adactive_sas_saml2_bridge.logout.handler]