#
# Configuration file for the AdminLTE bundle
#
# For more information about the settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
admin_lte:
    options:
        default_avatar: bundles/adminlte/images/default_avatar.png
        fixed_layout: false
        boxed_layout: true
        collapsed_sidebar: false
        mini_sidebar: true

    control_sidebar:
        home:
            icon: fas fa-home
            template: control-sidebar/home.html.twig
        settings:
            icon: fas fa-cogs
            controller: 'App\Controller\DefaultController::userPreferences'

#    theme:
#        widget:
#            type: warning
#            bordered: true
#            collapsible: truesonata_admin_dashboard
#            collapsible_title: 'Collapse'
#            removable: false
#            removable_title: 'Remove'
#            solid: false
#            use_footer: false
#        button:
#            type: 'primary'
#            size: false

    knp_menu:
        enable: false
        # the default value is adminlte_main, so we don't need to set it manually
        #main_menu: adminlte_main
        breadcrumb_menu: true

    routes:
        adminlte_welcome: sonata_admin_dashboard
        adminlte_login: sonata_login
        adminlte_login_check: fos_user_security_check
        adminlte_registration: fos_user_registration_register
        adminlte_password_reset: fos_user_resetting_request
        adminlte_message: admin_app_timelineentry_edit
        adminlte_messages: admin_app_timelineentry_list
        adminlte_notification: sonata_admin_dashboard
        adminlte_notifications: sonata_admin_dashboard
        adminlte_task: admin_app_taak_edit
        adminlte_tasks: admin_app_taak_list
        adminlte_profile: fos_user_profile_show
