admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /%sonata_prefix%

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /%sonata_prefix%