#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_routes:
    resource: 'authentication_route_loader:load'
    type: service

authentication:
    resource: .
    type: authentication

authentication_token:
    path: /authentication_token
    methods: ['POST']
    
#hslavich_saml_sp:
#    resource: "@HslavichOneloginSamlBundle/Resources/config/routing.yml"